
/* Project Euler Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

/*
calculates the n-th Fibonacci-number
*/

"use strict"

function fibonacci(n) {

    let result = 0;

    if (n == 0 || n == 1) {
        result = 1;
    } else {
        return fibonacci(n-1) + fibonacci(n-2);
    }

    return result;
}

function addEvenFiboUntil(limit) {
    let sum = 0;
    let i = 1;

    while (fibonacci(i) < limit) {
        if (fibonacci(i) % 2 === 0) {
            sum += fibonacci(i);
        }
        i++;
    }

    return sum;
}
